name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FRR releases for ${{ matrix.os }}
      uses: metal-stack/action-docker-make@master
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        args: --no-lint --file docker-make.${{ matrix.os }}.yaml
