name: Docker Image from master

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build FRR releases for ${{ matrix.os }}
      uses: metal-stack/action-docker-make@master
      with:
        args: --no-lint --no-push --file docker-make.${{ matrix.os }}.yaml
